language: csharp
mono: none
dotnet: 5.0
solution: NameSorterSolution/NameSorterSolution.sln

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test NameSorter.Tests/NameSorter.Tests.csproj
